# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3156462a5dbbcd6b7a524770bd2d3b0ea0591bfc7dd2fd06be120cfb266823c3fc9ff549bdf2579cac03e77f6b6e8a84e3b901778e54ab8dee90ce4763a65ec5
  # aws_bucket_name: bucket-name
  # aws_access_key_id: access-key-id
  # aws_secret_access_key: access-key

test:
  secret_key_base: 3156462a5dbbcd6b7a524770bd2d3b0ea0591bfc7dd2fd06be120cfb266823c3fc9ff549bdf2579cac03e77f6b6e8a84e3b901778e54ab8dee90ce4763a65ec5
  # aws_bucket_name: bucket-name
  # aws_access_key_id: access-key-id
  # aws_secret_access_key: access-key

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  # aws_bucket_name: <%= ENV['aws_bucket_name'] %>
  # aws_access_key_id: <%= ENV['aws_access_key_id'] %>
  # aws_secret_access_key: <%= ENV['aws_secret_access_key'] %>
